### ISSUE TITLE
how can i convert the text files to yolo darkflow version xml files ?

### ISSUE THREAD

**Issue by INNFINITEMINDS** [Cartucho/OpenLabeling#15]

**Comment by Cartucho** [comment]
I never used darkflow, what do you mean?
Please provide some description.

**Comment by INNFINITEMINDS** [comment]
for tarining our own data by using darkflow (it iss a tensorflow implememtaion of darknet) so after annoataing images and generating text file how can we convert that to xml file for training purpose ?

**Comment by Cartucho** [comment]
ok, got it. But what is the structure required for those xml files?

**Comment by andikira** [comment]
i'm noob in computer vision, but i'll try to answer your question
I think you can try using labelimg in this repo https://github.com/tzutalin/labelImg 
i hope @Cartucho labelbox can generate xml file to

**Comment by Cartucho** [comment]
@INNFINITEMINDS  you already have the txt files and want to convert to xml ones right? I can help you with that, just give me some details on how the xml's are structured

**Comment by INNFINITEMINDS** [comment]
the below xml file generated for single class /for single object for example to detect single objectt like fidget spiiner in image

==================
here is the xml generated file::

<annotation>
  <folder>images</folder>
  <filename>000000013.png</filename>
  <segmented>0</segmented>
  <size>
    <width>312</width>
    <height>151</height>
    <depth>3</depth>
  </size>
</annotation>

**Comment by bhavykhatri** [comment]
@INNFINITEMINDS Can you give your text file format. I will see if I can convert them into xml file.

**Comment by jatinmandav** [comment]
Hi @INNFINITEMINDS ,
Hope this will do the task.! [generating XML files from .txt files.](https://github.com/Cartucho/OpenLabeling/pull/21)
