### ISSUE TITLE
Image not load when pressing "D" on MacOS

### ISSUE THREAD

**Issue by n5ken** [Cartucho/OpenLabeling#17]
I am using Mac High Sierra v10.13.2 when I press "D" to the next page, the track bar moves to the next item but the image is still the previous one, it works well on Ubuntu.

**Comment by Cartucho** [comment]
And changing the class, for example, works? Pressing "W" or "S"

**Comment by robsalasco** [comment]
+1 I have this bug too! hope you can fix it :)

**Comment by Cartucho** [comment]
@robsalasco thank you for your report! Are you also using a Macbook?

**Comment by robsalasco** [comment]
@Cartucho yep I'm using macOS too

**Comment by chris3240** [comment]
Same with me. I can change the classes, but not the images. However, labeling files get created for each image

**Comment by Cartucho** [comment]
Can you try changing in the code to another letter? 
` pressed_key == ord('d')`,

for example, you could try changing it to ` pressed_key == ord('e')`

**Comment by chris3240** [comment]
Doesn't change anything. If I press D, the bar of the selected image is moving, but the same image is displayed. Yesterday it somehow worked for one try, but after that I had the same issue. Can't reproduce this

**Comment by chris3240** [comment]
I get a message in my console "OpenCV: Couldn't read video stream from file "input/.DS_Store"". I'm trying to label .jpg images, no video frames.

**Comment by n5ken** [comment]
> I get a message in my console "OpenCV: Couldn't read video stream from file "input/.DS_Store"". I'm trying to label .jpg images, no video frames.

You can try my workaround to remove call back from `cv2.createTrackbar(...)`

**Comment by n5ken** [comment]
> Can you try changing in the code to another letter?
> ` pressed_key == ord('d')`,
> 
> for example, you could try changing it to ` pressed_key == ord('e')`

I tried before but with no luck

**Comment by chris3240** [comment]
Okay, I found out, that only the Key Listener seems to not work. As soon as I use the Keys (which one I use doesn't matter) the image is not changing, but if I drag the bar, the image changes. Also, if I press the Key to change the image too often the program crashes with 

> ValueError: Fungus Venturia inaequalis' is not in 

 which indeed is no longer in my list of classes

**Comment by chris3240** [comment]
Okay, I think I found the solution. I call `set_img_index(img_index)` after decreasing, or increasing the key right before `1035: cv2.setTrackbarPos(TRACKBAR_IMG, WINDOW_NAME, img_index)`

**Comment by Cartucho** [comment]
cool! so it works now?

**Comment by Cartucho** [comment]
@n5ken @chris3240 do you think you could give it a try now? (maybe re-clone the repo in another directory)

**Comment by chris3240** [comment]
Yeah, it works. Thanks for providing this tool and your help!
