### ISSUE TITLE
bug on deleting bounding box?

### ISSUE THREAD

**Issue by steeler18** [Cartucho/OpenLabeling#24]
I am not sure if this is a bug or by design.

(1) When I selected an existing bounding box by double clicking inside its area, the box was selected and the delete button appeared at its upper right corner. At this point _prev_was_double_click_ was set to True. 
(2) Then I clicked on the delete button, _prev_was_double_click_ was set to False and this is "Finish double click" according to the comment. Nothing happened on the UI.
(3) Then I needed to click on the delete button again in order to delete that bounding box.

So we need to left click twice to delete. Is this by design?

**Comment by Cartucho** [comment]
That definitely sounds like a bug! I will fix it tomorrow!

**Comment by Cartucho** [comment]
Hello, it should be working now! Could you please give it a try?
You can update it by using `git pull origin master` in the terminal or clone it again.
