### ISSUE TITLE
How to change the label of the selected box?

### ISSUE THREAD

**Issue by ehsanfathi77** [Cartucho/OpenLabeling#28]
How can I select a box and change the label without drawing an new box?

**Comment by Cartucho** [comment]
Hello, currently that is not possible. But I will be adding that feature.
I will let you know when ready.

**Comment by seanthegreat7** [comment]
I just added a pull request #29 which adds this ability.

**Comment by Cartucho** [comment]
Issue solved. Just press `w` or `s` with the bounding box selected.
