### ISSUE TITLE
Mouse cursor delay

### ISSUE THREAD

**Issue by seanthegreat7** [Cartucho/OpenLabeling#30]
is there a way to decrease the mouse cursor delay?

**Comment by Cartucho** [comment]
Hey, I just added a parameter for the delay.

I reduced the default delay from `50` to `20` milliseconds.

**Comment by Cartucho** [comment]
In my case it did. So there are two sources of delay:

1. The wait for the keyboard (this one we can just tune it as we want)
2. The processing it takes to load the image, draw the lines and the boxes.

Images are getting re-drawn every single time, so with large images (high resolution), this can cause a significant delay.
