### ISSUE TITLE
Bug in click-drag resizing

### ISSUE THREAD

**Issue by vuthede** [Cartucho/OpenLabeling#45]
I have found a minor bug on click-drag resizing. 
The steps are:
+ Label the bboxes (more than one bbox)
+ Press 'p' to predict next frames
+ Click-drag resize on one of labelled bbox -> Bug in here.
Please see this video for the bug
https://drive.google.com/file/d/1jG3DBnOdGQ6mOEuH048M4oEC1DkWNto9/view?usp=sharing

**Comment by Cartucho** [comment]
Hello! I just [solved it](https://github.com/Cartucho/OpenLabeling/commit/05d7f8a3b2244cd6626be302a67d4d48895a434a).

Basically, it was selecting the wrong one.

**Comment by vuthede** [comment]
Hello! Yeah! thanks, i tried it again, it work smoothly!
