### ISSUE TITLE
Can`t caprure small objects

### ISSUE THREAD

**Issue by tarasevich-dmitry** [Cartucho/OpenLabeling#46]
Hello,
I can't capture some small objects with bounding box, it's just impossible to set it.  However when I try a bit bigger box (that is out of size of my object) it works, looks like it is some limit. See screens attached. 
Any suggestions?

OpenCV version '3.4.5'

![4-44](https://user-images.githubusercontent.com/26335004/52857627-612c5f80-3130-11e9-8a41-e2f509c9c722.png)
![15 14-45-23](https://user-images.githubusercontent.com/26335004/52857628-612c5f80-3130-11e9-9718-9bf5e581fe1d.png)

**Comment by vuthede** [comment]
Hi @tarasevich-dmitry , I think you can adjust the minimize **threshold** of bounding box.
![screenshot from 2019-02-15 20-07-14](https://user-images.githubusercontent.com/19920599/52858749-98fdcc00-315d-11e9-95d5-fc24a6accf55.png)

**Comment by tarasevich-dmitry** [comment]
@vuthede Thanks for advice! 
But as it was mentioned in comment, is it some errors may occur with small size boxes?

**Comment by vuthede** [comment]
No problem! I think there would not be an  actual error when the bbox was small.
I guess the author of code just want to avoid some cases. For example, we draw some **very small** "wrong" bbox due to unexpected mouse-click event and we can not see it because it is very small.

**Comment by tarasevich-dmitry** [comment]
Ok, thanks ones again!
Guess I can close this issue now

**Comment by Cartucho** [comment]
Hello, yeah @vuthede is right, I added to avoid creating bounding boxes by mistake, since we don't have a "go back" or `ctrl + z`  feature yet. I will reduce the threshold from 20 to 10!
