### ISSUE TITLE
GOTURN Tracker not working

### ISSUE THREAD

**Issue by reeldata** [Cartucho/OpenLabeling#47]
When I change GOTURN tracker in main.py, run the program, select a bounding box, and press 'p', the program crashes with the following error message: 
`Traceback (most recent call last):
  File "main.py", line 1084, in <module>
    label_tracker.start_tracker(json_file_data, json_file_path, img_path, obj, color, annotation_formats)
  File "main.py", line 846, in start_tracker
    tracker.init(self.init_frame, initial_bbox)
cv2.error: OpenCV(3.4.5) /io/opencv/modules/dnn/src/caffe/caffe_io.cpp:1121: error: (-2:Unspecified error) FAILED: fs.is_open(). Can't open "goturn.prototxt" in function 'ReadProtoFromTextFile'`

Ubuntu 18.04 LTS, python 3.6.7, installed everything in a fresh virtualenv with requirements.txt

Thanks

**Comment by Cartucho** [comment]
Hello! Sorry that I was not able to help you. Did it had to do with the OpenCV version?

**Comment by reeldata** [comment]
Hey, thanks for checking in. 

No, it had to do with the fact that I hadn't properly set up OpenCV to run GOTURN. I got it to work in the end after doing that properly, but it turns out that GOTURN didn't cut it for the data I had to label (lots of very similar densely packed objects).

I actually ended up writing a wrapper class for the DaSiamRPN tracking model (https://github.com/foolwood/DaSiamRPN/) and extending this repository to be able to use it instead. This worked **_significantly_** better than any of the tracking methods currently available through OpenCV. I was thinking about submitting a PR for it, but I figured you were trying to keep this package restricted to using what is implemented by OpenCV. Let me know if you'd still like to take a look at it and I'll try to clean it up a bit and send it your way.

**Comment by Cartucho** [comment]
Hello! This repo is not restricted to OpenCV if you have a better alternative and we can find a way to use it here we can add it!  :1st_place_medal: 

And then it is up to the user to choose between using the OpenCV trackers or another one.
