### ISSUE TITLE
tracker

### ISSUE THREAD

**Issue by fybonacci** [Cartucho/OpenLabeling#49]
Hi!
I would like to use the tracker feature. Does it work now? 
If yes, how can I apply tracking for video, please.

Thank you.

**Comment by Gamesherd224** [comment]
All you have to do is put a bounding box around one object, and then press p on the keyboard. It will automatically predict where the object is in the following frames. Look at the readme for more info,

**Comment by skrish13** [comment]
how to predict on series of images?

**Comment by Cartucho** [comment]
@skrish13 just draw a bounding box and press `p` on the keyboard
