### ISSUE TITLE
To Save What is detected

### ISSUE THREAD

**Issue by Shreenivasjh** [Cartucho/OpenLabeling#54]
Is there any option such that if a person is detected then its should be saved in a file. Such that we can use the saved file to open a house gate(or door) when person is detected nearby using sensors

**Comment by Cartucho** [comment]
Hello, this tool is for labeling images and not an object detector.
If you want to implement that you will need to train and object detector for the person class.

**Comment by Shreenivasjh** [comment]
Sir we wanted to detect fruits and other objects which is already trained in your project. 
We wanted to detect an object and send that detected value to Raspberry Pi. Can this be done? Or is it possible ??

**Comment by Cartucho** [comment]
Yes, it can be done. But again, not with this tool.

**Comment by Shreenivasjh** [comment]
Thanks a lot sir.
