### ISSUE TITLE
Issues installing project after DaSiamRPN Update

### ISSUE THREAD

**Issue by fogx** [Cartucho/OpenLabeling#57]
Hey, thanks for this great project.

I was trying to use this tool today and noticed some errors:
- Since the update adding the DaSiamRPN, the installation now requires pytorch to run, as well as to download the correct DaSiamRPN. This is not a big issue, should be added to the installation guide though.
- The dasiamrpn.py file uses "torch.load(f)" which fails in its current state when no CUDA GPU is installed. 
- The dasiamrpn.py file links to the wrong DaSiamRPN, returning the the BIG network, which of course fails in execution because the tensors are too big (2x).
- Right now the SiamNetwork Code (in the submodule) uses a couple of CUDA commands. 
- When installing pytorch with conda, executing the main.py shows a warning about Qt not working. export QT_XKB_CONFIG_ROOT=/usr/share/X11/xkb  fixes this 

Would it make sense to not use the DaSiamRPN as submodule and change the code to have the cuda commands be optional?

**Comment by Cartucho** [comment]
Thank you, I will make the DaSiamRPN tracker not the default one.
