### ISSUE TITLE
DaSiamRPN files not found.

### ISSUE THREAD

**Issue by OzgunKB** [Cartucho/OpenLabeling#64]
How to solve?

Error: DaSiamRPN files not found. Please run the following command:
        git submodule update --init

**Comment by Cartucho** [comment]
Run this `git submodule update --init` on the terminal.

**Comment by fj0n** [comment]
> Run this `git submodule update --init` on the terminal.

I tried this out two, but it didn't work for. Also reinstalled all the necessary packages according to the requirements.txt

I use git in Version2.15.0

I'm thankful for every idea! :)

**Comment by 783767** [comment]
I did as stated and from the image below, after Running `git submodule update --init` in terminal, no luck

Duplicate of #64 
![Screenshot from 2020-01-17 16-19-19](https://user-images.githubusercontent.com/20387421/72619259-91ced780-3945-11ea-94b2-5214825b2bc7.png)
