### ISSUE TITLE
question regarding the output file

### ISSUE THREAD

**Issue by YeetMasterYeet** [Cartucho/OpenLabeling#74]
hello, i hope you are all doing well, i have a question concerning each single numeric value in the output file( yolo), what does each specific number mean? i was able to discover that the first digit of every line is the class id of the detected object but that's it, i also know that the following 4 numbers are the position of the object in question, and i want to have more details if possible about each value and what does it represent.
thanks!!!

**Comment by christian-cahig** [comment]
@YeetMasterYeet you might find this useful: https://albumentations.ai/docs/getting_started/bounding_boxes_augmentation/#different-annotations-formats

**Comment by YeetMasterYeet** [comment]
> @YeetMasterYeet you might find this useful: https://albumentations.ai/docs/getting_started/bounding_boxes_augmentation/#different-annotations-formats

thank you @christian-cahig, indeed useful.
